spring.application.name=WinterOlympics

spring.datasource.url=jdbc:mysql://localhost:3306/WinterOlympics
spring.datasource.username=root
spring.datasource.password=Lubo.st2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/WinterOlympicsRealm

keycloak.server-url=http://localhost:8081
keycloak.realm=WinterOlympicsRealm
keycloak.admin-client-id=spring-api
keycloak.admin-client-secret=5YyILz8wjIaPPqfgKX5A2nd1CF9bC0zZ
keycloak.target-client-id=spring-api